#!/bin/sh

set -eu

# bar settings
yabai -m config status_bar off

# global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow off
yabai -m config window_border off
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

# general space settings
yabai -m config layout bsp
